site_name: UABRC Docs

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  feature:
    tabs: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - Account Management:
    - 'account_management/uab_user.md'
    - 'account_management/xias_users.md'
    - 'account_management/xias_sites.md'
    - 'account_management/xias_guest.md'
  - Data Management:
    - 'data_management/storage.md'
    - File Transfer:
      - 'data_management/transfer/globus.md'
      - 'data_management/transfer/filezilla.md'