site_name: My Docs
theme: 
  name: readthedocs
  titles_only: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: 'index.md'
  - Account Management:
    - 'account_management/uab_user.md'
    - 'account_management/xias_users.md'
    - 'account_management/xias_sites.md'
    - 'account_management/xias_guest.md'