site_name: UABRC Docs

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  feature:
    tabs: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - table-reader:
      data_path: 'docs'

nav:
  - Home: 'index.md'
  - Account Management:
    - 'account_management/uab_user.md'
    - 'account_management/xias_users.md'
    - 'account_management/xias_sites.md'
    - 'account_management/xias_guest.md'
  - Data Management:
    - 'data_management/storage.md'
    - File Transfer:
      - 'data_management/transfer/globus.md'
      - 'data_management/transfer/filezilla.md'
  - Cheaha User Guide:
    - 'cheaha/index.md'
    - Hardware: 'cheaha/hardware.md'
    - Open OnDemand:
      - 'cheaha/open_ondemand/ood_main.md'
      - 'cheaha/open_ondemand/ood_interactive.md'
      - 'cheaha/open_ondemand/ood_files.md'
      - 'cheaha/open_ondemand/ood_jobs.md'
    - SLURM: 
      - Introduction: 'cheaha/slurm/index.md'
      - 'cheaha/slurm/sbatch_usage.md'
      - 'cheaha/slurm/gpu.md'
      - 'cheaha/slurm/job_management.md'
    - 'cheaha/lmod.md'
    - 'cheaha/conda.md'