site_name: UABRC Docs
repo_url: https://github.com/uabrc/researcher-facing-MkDocs

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  feature:
    tabs: true
  custom_dir: 'theme'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false

plugins:
  - search
  - table-reader:
      data_path: 'docs'

nav:
  - Home: 'index.md'
  - Welcome:
    - 'welcome/welcome.md'
    - 'welcome/rc_days.md'
  - Account Management:
    - 'account_management/uab_user.md'
    - 'account_management/xias_users.md'
    - 'account_management/xias_sites.md'
    - 'account_management/xias_guest.md'
  - Data Management:
    - 'data_management/storage.md'
    - File Transfer:
      - 'data_management/transfer/globus.md'
      - 'data_management/transfer/filezilla.md'
  - Cheaha User Guide:
    - 'cheaha/index.md'
    - Hardware: 'cheaha/hardware.md'
    - Open OnDemand:
      - 'cheaha/open_ondemand/ood_main.md'
      - 'cheaha/open_ondemand/ood_interactive.md'
      - 'cheaha/open_ondemand/ood_files.md'
      - 'cheaha/open_ondemand/ood_jobs.md'
    - SLURM: 
      - Introduction: 'cheaha/slurm/index.md'
      - 'cheaha/slurm/sbatch_usage.md'
      - 'cheaha/slurm/gpu.md'
      - 'cheaha/slurm/job_management.md'
    - 'cheaha/lmod.md'
    - 'cheaha/conda.md'
  - UAB Cloud:
    - Introduction: 'uab_cloud/index.md'
    - 'uab_cloud/network_setup_basic.md'
    - 'uab_cloud/instance_setup_basic.md'
    - 'uab_cloud/volume_setup_basic.md'